name: u24-arm-int

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: cpu info
        run: lscpu
      - name: uname
        run: uname -a
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

